services:
  postgres:
    image: postgres:16-alpine
    container_name: ophuaconnect-db
    environment:
      POSTGRES_USER: ophua
      POSTGRES_PASSWORD: ophua123
      POSTGRES_DB: ophuaconnect
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
