version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ophuaconnect-db
    environment:
      POSTGRES_USER: ophua
      POSTGRES_PASSWORD: ophua123
      POSTGRES_DB: ophuaconnect
    ports:
      - "5439:5432" # Porta 5439 no host -> 5432 no container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ophua -d ophuaconnect"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
